### ISSUE TITLE
How is broker.id generated?

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#141]
I've used this cookbook with kafka 8 and it works great. 
With kafka 10, the range for valid broker ID's changed and I get an error anytime kafka starts. 

The autogenerated broker ID is greater than the maximum number 

```
# Generated by Chef.
# Local modifications will be overwritten.

advertised.host.name=dev-kafka01.local
auto.create.topics.enable=true
broker.id=1664189637
default.replication.factor=3
delete.topic.enable=true
log.retention.hours=24
log.roll.hours=24
num.partitions=8
port=6667
reserved.broker.max.id=1000000000
```

broker.id=1664189637 # 10 digits
reserved.broker.max.id=1000000000 # 10 digits

Does this cookbook generate broker.id? or does kafka generate broker.id?

**Comment by spuder** [comment]
My quirky work around is to set `reserved_broker_max_id` and then use a node attribute to generate a random number once. 

```
default['kafka']['broker'] = {
  advertised_host_name: (node['fqdn'] || node['hostname']).to_s, 
  reserved_broker_max_id:  1_000_000_000
}

range = 1_000_000..1_000_000_000
node.set['kafka']['broker']['broker_id'] = rand(range) unless node['kafka']['broker']['broker_id']
```

**Comment by mthssdrbrg** [comment]
@spuder: What version are you using? In the latest released one (`2.2.2`), If you set the `node['kafka']['broker']['broker.id']` to `nil` this cookbook shouldn't generate any ID, and Kafka will itself generate an available ID.
If `node['kafka']['broker']['broker.id']` isn't set to anything this cookbook will generate an ID from the node's IP address (https://github.com/mthssdrbrg/kafka-cookbook/blob/v2.2.2/recipes/_defaults.rb#L8).

**Comment by spuder** [comment]
Could you release 2.2.2 with that change?

**Comment by mthssdrbrg** [comment]
`master` is the "development" branch, v2.x is maintained at the [`v2.x` branch](https://github.com/mthssdrbrg/kafka-cookbook/tree/v2.x).

Looking at it though, this change is already present in v2.2.1, but you need to explicitly set `broker_id` to `nil` otherwise this cookbook will generate an ID. So something like this _should_ work:

```
default['kafka']['broker'] = {
  advertised_host_name: Chef::Config[:node_name], 
  broker_id: nil
}
```

FWIW, v2.2.2 can be found [here](https://github.com/mthssdrbrg/kafka-cookbook/releases/tag/v2.2.2) or at the [Supermarket](https://supermarket.chef.io/cookbooks/kafka/versions/2.2.2).
