### ISSUE TITLE
Add support for advertised.host.name

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#75]
It would be nice if the config file could also set the advertised host name in the settings.properties

     advertised.host.name=foobar.example.com

**Comment by mthssdrbrg** [comment]
It's already possible to set that configuration option: `node.default.kafka.broker.advertised_host_name = 'foobar.example.com'` (or `node.default.kafka.broker['advertised.host.name'] = 'foobar.example.com'`, or `node.default.kafka.broker.advertised.host.name = 'foobar.example.com'`).

Suppose the docs could be improved regarding broker configuration. Let me know if you have any further issues with this, otherwise feel free to close this issue.

**Comment by spuder** [comment]
Thanks, 

I'm a little confused on the syntax though. I have a wrapper cookbook with a customize.rb that looks like this:

```ruby
default['java']['jdk_version'] = '7'

default['kafka']['version'] = '0.8.1.1'
# http://mirror.cogentco.com/pub/apache/kafka/0.8.2.0/kafka_2.10-0.8.2.0.tgz
default['kafka']['scala_version'] = '2.9.2'
default['kafka']['checksum'] = 'cb141c1d50b1bd0d741d68e5e21c090341d961cd801e11e42fb693fa53e9aaed'
default['kafka']['md5_checksum'] = '7541ed160f1b3aa1a5334d4e782ba4d3'

default['kafka']['heap_opts'] = '-Xmx1G -Xms1G'
default['kafka']['init_style'] = :upstart
default['kafka']['automatic_start'] = true

# This is a hash of values that will be added to the server.config file
default['kafka']['broker'] = {
  zookeeper_connect: 'example.com/foobar',
  zookeeper_connection_timeout_ms: 15_00,
  advertised.host.name: node['fqdn']
}
```

I'm trying the following syntaxes with no luck. 
```
default['kafka']['broker'] = {
...
  ['advertised']['host']['name'] = node['fqdn']
}
```
```
default['kafka']['broker'] = {
...
  advertised.host.name: node['fqdn']
}
```

Should that config line be inside the default[kafka][broker] hash?

**Comment by spuder** [comment]
I got it working with this syntax. 

```
default['kafka']['broker'] = {
...
  zookeeper_connection_timeout_ms: 15_00,
}
default['kafka']['broker']['advertised_host_name'] = node['fqdn']
