### ISSUE TITLE
Can we add support for kafka version 0.8.2 ?

### ISSUE THREAD

**Issue by jayeshu** [mthssdrbrg/kafka-cookbook#77]
Kafka version 0.8.2 is the latest.
Can we add support to install that ?

**Comment by mthssdrbrg** [comment]
There's support for installing 0.8.2, just change the `node.kafka.version` attribute, as well as the checksum related attributes (though that goes without saying).

Since there's a quite critical bug in 0.8.2 regarding high CPU usage in Kafka clusters with a lot of partitions (see [KAFKA-1952](https://issues.apache.org/jira/browse/KAFKA-1952)), I'll hold off on updating the default version that this cookbook specifies.
