### ISSUE TITLE
How to allocate memory to Kafka broker?

### ISSUE THREAD

**Issue by sagar1730** [mthssdrbrg/kafka-cookbook#90]
I have just manage to setup multi-node multi-broker (3 broker for each) Kafka cluster. So far I didn't test it on heavy dataflow, but I like to specify memory limits for each broker lets say 30% for each. Is it possible or Kafka manage this thing effectively for us?

**Comment by mthssdrbrg** [comment]
You can set the heap size for Kafka using the `heap_opts` [attribute](https://github.com/mthssdrbrg/kafka-cookbook/blob/master/attributes/default.rb#L73). It's also possible to get the amount of available memory from Chef, so to use 30% of the available memory you could use something like this:

```ruby
# Fair warning though, I haven't tested this code
memory = 0.3 * node.memory.total.gsub('kB', '').to_i).round / 1024
node.default.kafka.memory = %(-Xms#{memory}m -Xmx#{memory}m)
```

Otherwise you could just specify a fixed amount of megabytes / gigabytes.

**Comment by mthssdrbrg** [comment]
@sagar1730: did this solve your issue?

**Comment by sagar1730** [comment]
@mthssdrbrg Yeah, I went with different idea which served the purpose. I am also excited to test your code, will do it soon. Thanks a lot.
